[FIX] purchase: analytic account clears
To reproduce the issue:
1. In Accounting, settings, activate Analytic Accounting
2. Head over to the purchase module, create an RFQ
3. Add a POL to the RFQ, with an analytic account specified
4. Save the RFQ
5. Edit the RFQ, and change the Order Deadline
6. The analytic account in the POL has disappeared

Error: The analytic account should not disappear

When modifying the deadline, the analytic account was always
being replaced, even if the replacement was empty.

In the same version (14.0), the same fix can be found in AML:
https://github.com/odoo/odoo/blob/1dcd071b27779e7d6d8f536c7dce7002d27212ba/addons/account/models/account_move.py#L3583-L3584

In 16.0, the issue doesn't need to be fixed, as it has already
been fixed, by a similar fix, as seen in POL:
https://github.com/odoo/odoo/blob/c677f45dcb050ce7e6f755b71e56c9b9120bf613/addons/purchase/models/purchase.py#L1153

OPW-3159905

closes odoo/odoo#114326

Signed-off-by: Adrien Widart <awt@odoo.com>